services:
  qbit-manager:
    build:
      context: .
      dockerfile: Dockerfile
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Mount volumes
    volumes:
      - ./data/config:/app/config

      # Development: mount source code for live changes
      - ./src/my_qbit_manager:/app/src/my_qbit_manager:ro
    
    restart: unless-stopped
